# Generated by Django 5.2.4 on 2026-02-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile_date_of_birth'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('full_photo', models.ImageField(blank=True, null=True, upload_to='students/full_photos/')),
                ('school_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('on_transport', models.BooleanField(default=False)),
                ('on_school_lunch', models.BooleanField(default=False)),
                ('height_cm', models.PositiveIntegerField(blank=True, help_text='Height in centimeters', null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('tribe', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.grade')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parents.parent')),
                ('profile', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
