# Generated by Django 5.2 on 2025-11-24 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_topic_unique_together_book_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprehension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comprehension_images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehensions', to='Core.grade')),
            ],
        ),
    ]
