# Generated by Django 5.2 on 2025-11-24 21:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_comprehension'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehension',
            name='questions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprehension',
            name='story',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
