# Generated by Django 5.2.6 on 2025-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_comprehension_questions_comprehension_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
